# Setup
title:               salils blog
timezone: Asia/Kolkata
tagline:             'and writing space'
description:         'i write here sometimes. navigate using the tabs here. :)'
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Salil Parekh
  url:               https://twitter.com/burnedsap
  email:             salil458@gmail.com

# Gems
plugins:
  - jekyll-paginate

prose:
  rooturl: ''
  siteurl: http://www.burnedsap.github.io/
  media: assets
  metadata:
    _posts:
    - name: title
      field:
        label: title
        element: text
        value: title
    - name: layout
      field:
        label: layout
        element: text
        value: post
    - name: date
      field:
        label: date
        element: text
        value: CURRENT_DATETIME
    - name: author
      field:
        label: author
        element: text
        value: Salil
    - name: categories
      field:
        label: categories
        element: text
        placeholder: Enter categories separated by commas
    - name: tags
      field:
        label: tags
        element: text
        placeholder: Enter tags separated by commas
